name: Create Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Validate release tag
        id: release_ref
        uses: GregoryMachin/AtlassianPSVII.Standards/.github/actions/resolve-release-tag@c70eaec1e4d771fe56f9e0b378eda1e521db8a07 # v1.0.0

      - name: Download artifact from commit that got tagged
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: ci.yml
          workflow_conclusion: success
          commit: ${{ steps.release_ref.outputs.release_sha }}
          name: Release
          path: ./Release/
          if_no_artifact_found: fail

      - uses: GregoryMachin/AtlassianPSVII.Standards/.github/actions/setup-powershell@c70eaec1e4d771fe56f9e0b378eda1e521db8a07 # v1.0.0

      - uses: GregoryMachin/AtlassianPSVII.Standards/.github/actions/build-release-notes@c70eaec1e4d771fe56f9e0b378eda1e521db8a07 # v1.0.0
        id: release_notes
        with:
          release-version: ${{ steps.release_ref.outputs.release_tag }}

      - name: Publish module
        run: |
          Invoke-Build -Task Publish `
            -VersionToPublish ${{ steps.release_ref.outputs.release_tag }} `
            -PSGalleryAPIKey ${{ secrets.PSGALLERY_API_KEY }}
        shell: pwsh

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v3
        with:
          body_path: ${{ steps.release_notes.outputs.release_notes_path }}
          files: ./Release/JiraPSVII.zip
          fail_on_unmatched_files: true
          draft: false
          tag_name: ${{ steps.release_ref.outputs.release_tag }}
          name: ${{ steps.release_ref.outputs.release_tag }}
          prerelease: ${{ contains(steps.release_ref.outputs.release_tag, 'alpha') || contains(steps.release_ref.outputs.release_tag,
            'beta') || contains(steps.release_ref.outputs.release_tag, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
